name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build Docker image
      run: docker build -t factory-dashboardv1 .

    - name: Save Docker image to file
      run: docker save dashboardv1 | gzip > factory-dashboardv1.tar.gz

    - name: Copy Docker image to Raspberry Pi
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dashboardv1.tar.gz"
        target: "~/dashboardv1.tar.gz"

    - name: Load Docker image on Raspberry Pi
      run: |
        ssh ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "docker load -i ~/dashboardv1.tar.gz && rm ~/dashboardv1.tar.gz"

    - name: Run Docker container on Raspberry Pi
      run: |
        ssh ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "docker stop dashboardv1 || true && docker rm dashboardv1 || true && docker run -d -p 4173:4173 --restart unless-stopped --name dashboardv1 dashboardv1"
