name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/factory-dashboard:latest

    - name: SSH to Raspberry Pi and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.RPI_HOST }}
        port: ${{ secrets.RPI_PORT }}
        username: ${{ secrets.RPI_USER }}
        key: ${{ secrets.RPI_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/factory-dashboard:latest
          docker stop factory-dashboard || true
          docker rm factory-dashboard || true
          docker run -d -p 80:80 --name factory-dashboard ${{ secrets.DOCKER_USERNAME }}/factory-dashboard:latest
